# Generated by Django 5.0.2 on 2024-03-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnouncedPuResults",
            fields=[
                ("result_id", models.AutoField(primary_key=True, serialize=False)),
                ("polling_unit_uniqueid", models.CharField(max_length=50)),
                ("party_abbreviation", models.CharField(max_length=4)),
                ("party_score", models.IntegerField()),
                ("entered_by_user", models.CharField(max_length=50)),
                ("date_entered", models.DateTimeField()),
                ("user_ip_address", models.CharField(max_length=50)),
            ],
            options={"db_table": "announced_pu_results", "managed": False,},
        ),
        migrations.CreateModel(
            name="PollingUnit",
            fields=[
                ("uniqueid", models.AutoField(primary_key=True, serialize=False)),
                ("polling_unit_id", models.IntegerField()),
                ("ward_id", models.IntegerField()),
                ("lga_id", models.IntegerField()),
                ("uniquewardid", models.IntegerField(blank=True, null=True)),
                (
                    "polling_unit_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "polling_unit_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("polling_unit_description", models.TextField(blank=True, null=True)),
                ("lat", models.CharField(blank=True, max_length=255, null=True)),
                ("long", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "entered_by_user",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_entered", models.DateTimeField(blank=True, null=True)),
                (
                    "user_ip_address",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={"db_table": "polling_unit", "managed": False,},
        ),
        migrations.CreateModel(
            name="PollUnitResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("polling_unit_uniqueid", models.CharField(max_length=50)),
                ("party_abbreviation", models.CharField(default="", max_length=4)),
                ("party_score", models.IntegerField()),
                (
                    "polling_unit_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
